/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.restdsl.RestDslRuntimeModule;
import org.example.restdsl.RestDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RestDslIdeSetup extends RestDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RestDslRuntimeModule(), new RestDslIdeModule()));
	}
	
}
