/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.restdsl.ui.internal.RestdslActivator;

public class RestDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RestdslActivator.getInstance().getInjector("org.example.restdsl.RestDsl");
	}

}
