/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.example.restdsl.services.RestDslGrammarAccess;

@SuppressWarnings("all")
public class RestDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RestDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Operation_CreateKeyword_0_0_or_CustomEndpointKeyword_0_4_or_DeleteKeyword_0_3_or_ReadKeyword_0_1_or_UpdateKeyword_0_2;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RestDslGrammarAccess) access;
		match_Operation_CreateKeyword_0_0_or_CustomEndpointKeyword_0_4_or_DeleteKeyword_0_3_or_ReadKeyword_0_1_or_UpdateKeyword_0_2 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getOperationAccess().getCreateKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getOperationAccess().getCustomEndpointKeyword_0_4()), new TokenAlias(false, false, grammarAccess.getOperationAccess().getDeleteKeyword_0_3()), new TokenAlias(false, false, grammarAccess.getOperationAccess().getReadKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getOperationAccess().getUpdateKeyword_0_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Operation_CreateKeyword_0_0_or_CustomEndpointKeyword_0_4_or_DeleteKeyword_0_3_or_ReadKeyword_0_1_or_UpdateKeyword_0_2.equals(syntax))
				emit_Operation_CreateKeyword_0_0_or_CustomEndpointKeyword_0_4_or_DeleteKeyword_0_3_or_ReadKeyword_0_1_or_UpdateKeyword_0_2(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'create' | 'read' | 'update' | 'delete' | 'customEndpoint'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 
	 * </pre>
	 */
	protected void emit_Operation_CreateKeyword_0_0_or_CustomEndpointKeyword_0_4_or_DeleteKeyword_0_3_or_ReadKeyword_0_1_or_UpdateKeyword_0_2(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
