/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.restdsl.ui.internal.RestdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RestdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RestdslActivator activator = RestdslActivator.getInstance();
		return activator != null ? activator.getInjector(RestdslActivator.ORG_EXAMPLE_RESTDSL_RESTDSL) : null;
	}

}
