/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RestDslUiModule extends AbstractRestDslUiModule {

	public RestDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
