/**
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.restDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.restdsl.restDsl.Logic#getImplementation <em>Implementation</em>}</li>
 * </ul>
 *
 * @see org.example.restdsl.restDsl.RestDslPackage#getLogic()
 * @model
 * @generated
 */
public interface Logic extends EObject
{
  /**
   * Returns the value of the '<em><b>Implementation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implementation</em>' attribute.
   * @see #setImplementation(String)
   * @see org.example.restdsl.restDsl.RestDslPackage#getLogic_Implementation()
   * @model
   * @generated
   */
  String getImplementation();

  /**
   * Sets the value of the '{@link org.example.restdsl.restDsl.Logic#getImplementation <em>Implementation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implementation</em>' attribute.
   * @see #getImplementation()
   * @generated
   */
  void setImplementation(String value);

} // Logic
