/**
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.restDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.example.restdsl.restDsl.RestDslFactory
 * @model kind="package"
 * @generated
 */
public interface RestDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "restDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/restdsl/RestDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "restDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestDslPackage eINSTANCE = org.example.restdsl.restDsl.impl.RestDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.RestDslImpl <em>Rest Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.RestDslImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getRestDsl()
   * @generated
   */
  int REST_DSL = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_DSL__ENTITIES = 0;

  /**
   * The feature id for the '<em><b>Rest Apis</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_DSL__REST_APIS = 1;

  /**
   * The number of structural features of the '<em>Rest Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_DSL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.EntityImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FIELDS = 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.FieldImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getField()
   * @generated
   */
  int FIELD = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__TYPE = 1;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.RestApiImpl <em>Rest Api</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.RestApiImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getRestApi()
   * @generated
   */
  int REST_API = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API__NAME = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API__PATH = 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API__OPERATIONS = 2;

  /**
   * The number of structural features of the '<em>Rest Api</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.OperationImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__METHOD = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__PATH = 2;

  /**
   * The feature id for the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__REQUEST = 3;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RESPONSE = 4;

  /**
   * The feature id for the '<em><b>Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__LOGIC = 5;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.TypeImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getType()
   * @generated
   */
  int TYPE = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.restdsl.restDsl.impl.LogicImpl <em>Logic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.restdsl.restDsl.impl.LogicImpl
   * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getLogic()
   * @generated
   */
  int LOGIC = 6;

  /**
   * The feature id for the '<em><b>Implementation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC__IMPLEMENTATION = 0;

  /**
   * The number of structural features of the '<em>Logic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.RestDsl <em>Rest Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest Dsl</em>'.
   * @see org.example.restdsl.restDsl.RestDsl
   * @generated
   */
  EClass getRestDsl();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.restdsl.restDsl.RestDsl#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.example.restdsl.restDsl.RestDsl#getEntities()
   * @see #getRestDsl()
   * @generated
   */
  EReference getRestDsl_Entities();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.restdsl.restDsl.RestDsl#getRestApis <em>Rest Apis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rest Apis</em>'.
   * @see org.example.restdsl.restDsl.RestDsl#getRestApis()
   * @see #getRestDsl()
   * @generated
   */
  EReference getRestDsl_RestApis();

  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.example.restdsl.restDsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.restdsl.restDsl.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.restdsl.restDsl.Entity#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see org.example.restdsl.restDsl.Entity#getFields()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Fields();

  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.example.restdsl.restDsl.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.restdsl.restDsl.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Field#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.example.restdsl.restDsl.Field#getType()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Type();

  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.RestApi <em>Rest Api</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest Api</em>'.
   * @see org.example.restdsl.restDsl.RestApi
   * @generated
   */
  EClass getRestApi();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.RestApi#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.restdsl.restDsl.RestApi#getName()
   * @see #getRestApi()
   * @generated
   */
  EAttribute getRestApi_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.RestApi#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.example.restdsl.restDsl.RestApi#getPath()
   * @see #getRestApi()
   * @generated
   */
  EAttribute getRestApi_Path();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.restdsl.restDsl.RestApi#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.example.restdsl.restDsl.RestApi#getOperations()
   * @see #getRestApi()
   * @generated
   */
  EReference getRestApi_Operations();

  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.example.restdsl.restDsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Operation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.restdsl.restDsl.Operation#getName()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Operation#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.example.restdsl.restDsl.Operation#getMethod()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Method();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Operation#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.example.restdsl.restDsl.Operation#getPath()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Path();

  /**
   * Returns the meta object for the containment reference '{@link org.example.restdsl.restDsl.Operation#getRequest <em>Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Request</em>'.
   * @see org.example.restdsl.restDsl.Operation#getRequest()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Request();

  /**
   * Returns the meta object for the containment reference '{@link org.example.restdsl.restDsl.Operation#getResponse <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Response</em>'.
   * @see org.example.restdsl.restDsl.Operation#getResponse()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Response();

  /**
   * Returns the meta object for the containment reference '{@link org.example.restdsl.restDsl.Operation#getLogic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logic</em>'.
   * @see org.example.restdsl.restDsl.Operation#getLogic()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Logic();

  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.example.restdsl.restDsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Type#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.example.restdsl.restDsl.Type#getType()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Type();

  /**
   * Returns the meta object for class '{@link org.example.restdsl.restDsl.Logic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic</em>'.
   * @see org.example.restdsl.restDsl.Logic
   * @generated
   */
  EClass getLogic();

  /**
   * Returns the meta object for the attribute '{@link org.example.restdsl.restDsl.Logic#getImplementation <em>Implementation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Implementation</em>'.
   * @see org.example.restdsl.restDsl.Logic#getImplementation()
   * @see #getLogic()
   * @generated
   */
  EAttribute getLogic_Implementation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RestDslFactory getRestDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.RestDslImpl <em>Rest Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.RestDslImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getRestDsl()
     * @generated
     */
    EClass REST_DSL = eINSTANCE.getRestDsl();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST_DSL__ENTITIES = eINSTANCE.getRestDsl_Entities();

    /**
     * The meta object literal for the '<em><b>Rest Apis</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST_DSL__REST_APIS = eINSTANCE.getRestDsl_RestApis();

    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.EntityImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FIELDS = eINSTANCE.getEntity_Fields();

    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.FieldImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__TYPE = eINSTANCE.getField_Type();

    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.RestApiImpl <em>Rest Api</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.RestApiImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getRestApi()
     * @generated
     */
    EClass REST_API = eINSTANCE.getRestApi();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST_API__NAME = eINSTANCE.getRestApi_Name();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST_API__PATH = eINSTANCE.getRestApi_Path();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST_API__OPERATIONS = eINSTANCE.getRestApi_Operations();

    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.OperationImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__NAME = eINSTANCE.getOperation_Name();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__METHOD = eINSTANCE.getOperation_Method();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__PATH = eINSTANCE.getOperation_Path();

    /**
     * The meta object literal for the '<em><b>Request</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__REQUEST = eINSTANCE.getOperation_Request();

    /**
     * The meta object literal for the '<em><b>Response</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__RESPONSE = eINSTANCE.getOperation_Response();

    /**
     * The meta object literal for the '<em><b>Logic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__LOGIC = eINSTANCE.getOperation_Logic();

    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.TypeImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__TYPE = eINSTANCE.getType_Type();

    /**
     * The meta object literal for the '{@link org.example.restdsl.restDsl.impl.LogicImpl <em>Logic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.restdsl.restDsl.impl.LogicImpl
     * @see org.example.restdsl.restDsl.impl.RestDslPackageImpl#getLogic()
     * @generated
     */
    EClass LOGIC = eINSTANCE.getLogic();

    /**
     * The meta object literal for the '<em><b>Implementation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGIC__IMPLEMENTATION = eINSTANCE.getLogic_Implementation();

  }

} //RestDslPackage
