/**
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.restDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rest Dsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.restdsl.restDsl.RestDsl#getEntities <em>Entities</em>}</li>
 *   <li>{@link org.example.restdsl.restDsl.RestDsl#getRestApis <em>Rest Apis</em>}</li>
 * </ul>
 *
 * @see org.example.restdsl.restDsl.RestDslPackage#getRestDsl()
 * @model
 * @generated
 */
public interface RestDsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link org.example.restdsl.restDsl.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see org.example.restdsl.restDsl.RestDslPackage#getRestDsl_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Rest Apis</b></em>' containment reference list.
   * The list contents are of type {@link org.example.restdsl.restDsl.RestApi}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rest Apis</em>' containment reference list.
   * @see org.example.restdsl.restDsl.RestDslPackage#getRestDsl_RestApis()
   * @model containment="true"
   * @generated
   */
  EList<RestApi> getRestApis();

} // RestDsl
