/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.restdsl.parser.antlr.internal.InternalRestDslParser;
import org.example.restdsl.services.RestDslGrammarAccess;

public class RestDslParser extends AbstractAntlrParser {

	@Inject
	private RestDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRestDslParser createParser(XtextTokenStream stream) {
		return new InternalRestDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RestDsl";
	}

	public RestDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RestDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
