/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRestDslScopeProvider extends DelegatingScopeProvider {
}
