/**
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.restDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.restdsl.restDsl.Entity;
import org.example.restdsl.restDsl.RestApi;
import org.example.restdsl.restDsl.RestDsl;
import org.example.restdsl.restDsl.RestDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rest Dsl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.restdsl.restDsl.impl.RestDslImpl#getEntities <em>Entities</em>}</li>
 *   <li>{@link org.example.restdsl.restDsl.impl.RestDslImpl#getRestApis <em>Rest Apis</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RestDslImpl extends MinimalEObjectImpl.Container implements RestDsl
{
  /**
   * The cached value of the '{@link #getEntities() <em>Entities</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntities()
   * @generated
   * @ordered
   */
  protected EList<Entity> entities;

  /**
   * The cached value of the '{@link #getRestApis() <em>Rest Apis</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRestApis()
   * @generated
   * @ordered
   */
  protected EList<RestApi> restApis;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RestDslImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestDslPackage.Literals.REST_DSL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Entity> getEntities()
  {
    if (entities == null)
    {
      entities = new EObjectContainmentEList<Entity>(Entity.class, this, RestDslPackage.REST_DSL__ENTITIES);
    }
    return entities;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RestApi> getRestApis()
  {
    if (restApis == null)
    {
      restApis = new EObjectContainmentEList<RestApi>(RestApi.class, this, RestDslPackage.REST_DSL__REST_APIS);
    }
    return restApis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RestDslPackage.REST_DSL__ENTITIES:
        return ((InternalEList<?>)getEntities()).basicRemove(otherEnd, msgs);
      case RestDslPackage.REST_DSL__REST_APIS:
        return ((InternalEList<?>)getRestApis()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestDslPackage.REST_DSL__ENTITIES:
        return getEntities();
      case RestDslPackage.REST_DSL__REST_APIS:
        return getRestApis();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestDslPackage.REST_DSL__ENTITIES:
        getEntities().clear();
        getEntities().addAll((Collection<? extends Entity>)newValue);
        return;
      case RestDslPackage.REST_DSL__REST_APIS:
        getRestApis().clear();
        getRestApis().addAll((Collection<? extends RestApi>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestDslPackage.REST_DSL__ENTITIES:
        getEntities().clear();
        return;
      case RestDslPackage.REST_DSL__REST_APIS:
        getRestApis().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestDslPackage.REST_DSL__ENTITIES:
        return entities != null && !entities.isEmpty();
      case RestDslPackage.REST_DSL__REST_APIS:
        return restApis != null && !restApis.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RestDslImpl
