/*
 * generated by Xtext 2.32.0
 */
package org.example.restdsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class RestDslProposalProvider extends AbstractRestDslProposalProvider {
}
